### ISSUE TITLE
Store init scripts as their own `.sh` or `.bash` file and then read it in, rather than storing it as one big string directly in the code

### ISSUE THREAD

**Issue by cSchubes** [autognc/bran#7]
kind of a nit, but curious if it would be possible to store this script as its own `.sh` or `.bash` file and then read it in with this function, rather than storing it as one big string directly in the code? It would make maintaining the script easier since you would get actual syntax highlighting, etc when editing it.

For the formatting part, you can accomplish the same thing by placing specific identifiers into the separate script (like `<key_id>`) and then replacing them in the loaded string. This is done in the BBOX plugin, see here: https://github.com/autognc/ravenML-train-plugins/blob/master/rmltraintfbbox/rmltraintfbbox/utils/helpers.py#L129

definitely not critical, but could be nice

_Originally posted by @cSchubes in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjkxMDIxOTcxOnYy/pull_request_review_threads/discussion_

**Comment by jacobDeutsch10** [comment]
Got this implemented on the raven-tf2 branch. Need to do some more thorough testing before merging. Going to go ahead and close this issue though
